"""Pre-engine bootstrap boundary for the legacy ORM-based initial migration.

Only 0001 uses this copy. New engine schema must be built by its real revisions.
Existing legacy migrations retain their pre-0197 create/check compatibility.
"""
from sqlalchemy import MetaData, UniqueConstraint


LEGACY_BOOTSTRAP_TABLES = frozenset((
    "account_clone_items",
    "account_clone_plans",
    "account_eligibility_events",
    "account_environment_bindings",
    "account_group_admission_facts",
    "account_group_proxy_bindings",
    "account_pacing_reservations",
    "account_pools",
    "account_proxies",
    "account_proxy_bindings",
    "account_proxy_warmup_states",
    "account_runtime_summary",
    "action_terminal_daily_stats",
    "actions",
    "activation_codes",
    "adult_subject_attestations",
    "ai_account_group_stance_memory",
    "ai_account_voice_profile_generation_attempts",
    "ai_account_voice_profile_generation_items",
    "ai_account_voice_profile_generation_jobs",
    "ai_account_voice_profiles",
    "ai_content_policy_versions",
    "ai_content_scope_takeover_batches",
    "ai_content_scope_takeover_items",
    "ai_content_window_plan_slots",
    "ai_content_window_plans",
    "ai_coverage_variation_intents",
    "ai_drafts",
    "ai_generation_contract_audits",
    "ai_group_content_allocation_plans",
    "ai_group_content_intents",
    "ai_group_message_memory",
    "ai_provider_attempts",
    "ai_providers",
    "ai_usage_ledgers",
    "app_users",
    "archived_members",
    "archived_messages",
    "audit_logs",
    "authorization_dr_execution_nodes",
    "authorization_dr_runtime_contracts",
    "avatar_material_sources",
    "bot_protocol_samples",
    "campaign_processed_messages",
    "campaigns",
    "channel_comment_capacity_allocation_epochs",
    "channel_comment_content_revision_operations",
    "channel_comment_eligible_account_snapshot_rows",
    "channel_comment_fallback_pool_snapshots",
    "channel_comment_grounding_assignments",
    "channel_comment_grounding_enrollments",
    "channel_comment_grounding_evaluations",
    "channel_comment_grounding_snapshots",
    "channel_comment_listener_error_events",
    "channel_comment_ordinal_account_bindings",
    "channel_comment_plan_contracts",
    "channel_comment_plan_lifecycle_events",
    "channel_comment_quality_target_revisions",
    "channel_comment_recovery_manifests",
    "channel_discussion_group_bindings",
    "channel_discussion_group_probe_events",
    "channel_discussion_thread_bindings",
    "channel_discussion_thread_probe_events",
    "channel_message_comments",
    "channel_message_source_revisions",
    "channel_messages",
    "channel_view_daily_identity_owners",
    "channel_view_daily_message_targets",
    "clone_account_slots",
    "clone_album_items",
    "clone_album_manifests",
    "clone_cutover_exclusions",
    "clone_delivery_obligations",
    "clone_manual_review_decisions",
    "clone_message_parts",
    "clone_sender_binding_history",
    "clone_sequencer_head_cases",
    "clone_source_events",
    "clone_source_stream_states",
    "clone_target_execution_snapshots",
    "clone_target_route_snapshots",
    "clone_topic_maps",
    "comment_fallback_policy_snapshots",
    "comment_fallback_selections",
    "comment_fulfillment_obligations",
    "consistency_quarantines",
    "content_keyword_rules",
    "content_mix_contracts",
    "content_mix_cycle_slots",
    "content_mix_cycles",
    "content_mix_obligations",
    "context_scope_revisions",
    "conversation_speaker_states",
    "conversation_speaker_turns",
    "daily_runtime_stats",
    "developer_app_slot_assignments",
    "discussion_membership_facts",
    "dispatch_allocation_exclusions",
    "dispatch_allocation_release_batch_items",
    "dispatch_allocation_release_batches",
    "dispatch_claim_reservations",
    "dispatch_claim_scopes",
    "dispatch_claim_shard_allocations",
    "dispatch_claim_task_allocations",
    "dispatch_claim_windows",
    "dispatch_fairness_cursors",
    "dispatch_runtime_shard_states",
    "execution_attempts",
    "fallback_shuffle_bag_cursors",
    "fingerprint_combo_history",
    "fulfillment_fact_projection_states",
    "fulfillment_obligation_projections",
    "fulfillment_remote_facts",
    "fulfillment_shortfall_facts",
    "gateway_request_evidence_journals",
    "generation_jobs",
    "group_archives",
    "group_bot_admission_observations",
    "group_bot_admission_policies",
    "group_bot_admissions",
    "group_bot_required_channel_follows",
    "group_context_messages",
    "listener_channel_snapshot_items",
    "listener_source_state",
    "manual_operation_records",
    "material_asset_versions",
    "material_cache_configs",
    "material_groups",
    "material_import_jobs",
    "material_tg_ref_versions",
    "materials",
    "message_fingerprints",
    "message_task_attempts",
    "message_tasks",
    "operation_issue",
    "operation_issue_accounts",
    "operation_issue_sources",
    "operation_plan_generation_runs",
    "operation_plan_targets",
    "operation_plan_task_links",
    "operation_plan_templates",
    "operation_targets",
    "operation_task_attempts",
    "operation_tasks",
    "pending_visibility_credits",
    "prompt_templates",
    "proxy_airport_nodes",
    "proxy_airport_subscriptions",
    "proxy_alerts",
    "proxy_exit_ip_observations",
    "proxy_health_checks",
    "proxy_node_failover_events",
    "reaction_fulfillment_obligations",
    "reaction_remote_facts",
    "recoverable_work_leases",
    "remote_mutation_tombstones",
    "remote_reconcile_cases",
    "review_queue",
    "rule_set_versions",
    "rule_sets",
    "runtime_cleanup_audits",
    "runtime_metric_snapshots",
    "scheduling_settings",
    "search_click_assignment_epochs",
    "search_click_assignments",
    "search_click_fulfillment_obligations",
    "search_click_opportunity_assignments",
    "search_click_solver_carrier_unit_bindings",
    "search_click_solver_problem_components",
    "search_click_solver_problem_snapshots",
    "search_click_task_fairness_states",
    "search_join_linked_task_dispatches",
    "search_join_pacing_decisions",
    "search_join_protocol_traces",
    "search_join_rank_observations",
    "search_protocol_sessions",
    "search_rank_deboost_action_stats",
    "search_rank_deboost_alerts",
    "search_rank_deboost_click_reservations",
    "search_rank_deboost_exempt_groups",
    "source_media_assets",
    "source_pacing_admissions",
    "source_pacing_capacity_plans",
    "source_pacing_capacity_policy_versions",
    "source_pacing_states",
    "subscription_plans",
    "target_learning_profile_versions",
    "target_learning_profiles",
    "target_learning_samples",
    "target_membership_challenge_attempts",
    "target_runtime_summary",
    "task_account_daily_coverage",
    "task_admission_projections",
    "task_ai_content_policy_bindings",
    "task_comment_capacity_periods",
    "task_comment_capacity_reservations",
    "task_contract_activation_manifests",
    "task_contract_routes",
    "task_daily_coverage_plan_cursors",
    "task_daily_fulfillment_decisions",
    "task_day_ledger_lifecycle_events",
    "task_day_ledgers",
    "task_delete_operation_items",
    "task_delete_operations",
    "task_group_bot_admissions",
    "task_group_daily_message_slots",
    "task_group_daily_targets",
    "task_hard_hourly_buckets",
    "task_hard_hourly_delivery_credits",
    "task_membership_admission_items",
    "task_planner_wake_states",
    "task_runtime_active_blockers",
    "task_runtime_summary",
    "task_source_subscriptions",
    "task_start_operations",
    "tasks",
    "telegram_authorization_transport_states",
    "telegram_authorization_update_deliveries",
    "telegram_authorization_update_events",
    "telegram_authorization_update_states",
    "telegram_authorization_update_subscriptions",
    "telegram_bot_conversations",
    "telegram_developer_apps",
    "telegram_egress_assignments",
    "telegram_gateway_mutation_identities",
    "telegram_group_mutation_authorities",
    "telegram_group_mutation_authority_holders",
    "telegram_outbound_random_id_mappings",
    "tenant_ai_provider_route_items",
    "tenant_ai_provider_route_sets",
    "tenant_ai_settings",
    "tenant_learning_profile_versions",
    "tenant_learning_profiles",
    "tenant_learning_quality_rules",
    "tenant_learning_runs",
    "tenant_learning_samples",
    "tenant_learning_sources",
    "tenants",
    "tg_account_authorization_snapshots",
    "tg_account_authorizations",
    "tg_account_device_cleanup_prechecks",
    "tg_account_device_cleanup_targets",
    "tg_account_full_initializations",
    "tg_account_login_batch_attempts",
    "tg_account_login_batch_items",
    "tg_account_login_batch_notifications",
    "tg_account_login_batches",
    "tg_account_login_post_init_bindings",
    "tg_account_login_rate_buckets",
    "tg_account_online_state",
    "tg_account_phone_fingerprint_aliases",
    "tg_account_profile_batch_rules",
    "tg_account_profile_name_claims",
    "tg_account_profile_sync_records",
    "tg_account_security_batch_items",
    "tg_account_security_batches",
    "tg_account_security_snapshots",
    "tg_account_sync_records",
    "tg_accounts",
    "tg_authorization_dr_batch_items",
    "tg_authorization_dr_batches",
    "tg_authorization_dr_operations",
    "tg_authorization_dr_reconcile_cases",
    "tg_authorization_dr_stage_facts",
    "tg_authorization_local_activate_cases",
    "tg_authorization_online_abc_batches",
    "tg_authorization_online_abc_items",
    "tg_authorization_online_abc_slot_results",
    "tg_authorization_restore_probe_facts",
    "tg_authorization_slot_decisions",
    "tg_authorization_wake_bundle_copies",
    "tg_authorization_wake_bundles",
    "tg_authorization_wake_inventory_entries",
    "tg_contacts",
    "tg_group_accounts",
    "tg_groups",
    "tg_login_flows",
    "tg_post_login_abc_requests",
    "tg_verification_codes",
    "user_token_ledgers",
    "verification_tasks",
    "view_fulfillment_obligations",
    "view_remote_facts",
    "worker_heartbeats",
    "worker_runtime_resource_rollups",
    "worker_runtime_resource_samples",
))

ENGINE_ADDED_COLUMNS = {
    "channel_messages": frozenset(("grouped_id", "source_metadata")),
    "account_pacing_reservations": frozenset(("action_class",)),
    "task_group_daily_message_slots": frozenset(("continuity_claim_id", "quantity_credit_eligible")),
    "channel_message_comments": frozenset(("discussion_peer_id",)),
    "channel_comment_plan_contracts": frozenset((
        "task_day_ledger_id", "daily_participation_plan_id", "planning_admission_snapshot_id",
        "source_participation_plan_id", "source_journey_plan_id",
        "rounded_required_distinct_account_count", "realized_participation_bps", "integer_quantization_adjustment",
    )),
    "task_group_daily_targets": frozenset((
        "participation_plan_id", "planning_admission_snapshot_id", "quantity_policy_revision",
        "quantity_seed", "sampled_jitter_bps", "raw_quantity_target",
    )),
}


def legacy_bootstrap_metadata(source):
    metadata = MetaData()
    for name in sorted(LEGACY_BOOTSTRAP_TABLES):
        source.tables[name].to_metadata(metadata)
    generation_jobs = metadata.tables["generation_jobs"]
    generation_jobs.indexes.difference_update({index for index in generation_jobs.indexes
                                             if index.name == "ix_generation_job_provider_lineage"})
    attempts = metadata.tables["execution_attempts"]
    attempts.indexes.difference_update({index for index in attempts.indexes
                                      if index.name == "ix_execution_attempts_account_usage"})
    for name, excluded in ENGINE_ADDED_COLUMNS.items():
        table = metadata.tables[name]
        constraints, indexes, foreign_keys = _later_objects(table, excluded)
        table.constraints.difference_update(constraints)
        table.indexes.difference_update(indexes)
        table.foreign_keys.difference_update(foreign_keys)
        for column_name in excluded:
            # Only this local clone changes; live ORM metadata stays intact.
            table._columns.remove(table.c[column_name])
    metadata.tables["channel_message_comments"].append_constraint(UniqueConstraint(
        "tenant_id", "channel_target_id", "channel_message_id", "comment_message_id",
        name="uq_channel_message_comment_legacy_identity",
    ))
    return metadata


def _later_objects(table, excluded):
    constraints = {item for item in table.constraints
                   if any(column.name in excluded for column in item.columns)}
    indexes = {item for item in table.indexes
               if any(column.name in excluded for column in item.columns)}
    foreign_keys = {element for item in constraints for element in getattr(item, "elements", ())}
    return constraints, indexes, foreign_keys
