export type TaskCenterTaskType = 'group_ai_chat' | 'group_relay' | 'group_membership_admission' | 'channel_view' | 'channel_like' | 'channel_comment' | 'search_join_group' | 'search_rank_deboost';
export type TaskCenterSystemTaskType = 'account_profile_init' | 'account_device_cleanup' | 'account_2fa_setup' | 'account_standby_session_provision';
export type TaskCenterAnyTaskType = TaskCenterTaskType | TaskCenterSystemTaskType;

export type HardHourlyStrategy = 'force_planning';
export type HardHourlyStatus = 'disabled' | 'met' | 'catching_up' | 'blocked' | 'missed';

export type GroupAIChatHardHourlyConfig = {
  hard_hourly_target_enabled?: boolean;
  hourly_min_messages?: number | null;
  hard_hourly_strategy?: HardHourlyStrategy;
};

export type HardHourlyBlockers = Record<string, number>;
export type HardHourlyPipeline = Record<string, string>;

export type HardHourlyRecentBucket = {
  bucket: string;
  goal: number;
  success_count: number;
  future_open_count: number;
  open_count?: number;
  overdue_open_count: number;
  deficit: number;
  status: HardHourlyStatus;
  blockers?: HardHourlyBlockers;
};

export type TaskAccountCoverage = {
  mode?: 'natural' | 'all_accounts_daily';
  covered_count: number;
  confirmed_account_count?: number;
  eligible_count: number;
  target_account_count?: number;
  target_message_count?: number;
  confirmed_message_count?: number;
  remaining_count?: number;
  remaining_account_count?: number;
  remaining_message_count?: number;
  pending_admission_count?: number;
  restricted_count?: number;
  cannot_send_count?: number;
  offline_or_session_blocked_count?: number;
  blocked_count?: number;
  unknown_count?: number;
  unknown_after_send_count?: number;
  ready_count?: number;
  reserved_count?: number;
  target_per_account?: number;
  blocked_reasons?: Array<{ reason: string; count?: number; message?: string }>;
  estimated_completion_window?: { status: string; estimated_min_hours?: number | null; label: string };
  capacity_proof?: Record<string, any>;
  capacity_status?: 'sufficient' | 'blocked';
  required_daily_messages?: number;
  required_hourly_rate?: number;
  pending_accounts?: Array<{ account_id: number; display_name?: string; completed_count: number; target_count: number; remaining_count: number; reason: string }>;
  coverage_rate: number;
  coverage_percent: number;
  action_types: string[];
  statuses: string[];
};

export type TaskAccountCoverageItem = {
  id: string;
  account_id: number;
  display_name: string;
  username: string;
  coverage_date: string;
  target_count: number;
  confirmed_count: number;
  state: string;
  blocker_code: string;
  blocker_detail: string;
  reserved_action_id: string | null;
  last_success_action_id: string | null;
  last_remote_message_id: string;
  next_eligible_at: string | null;
  targeted_at: string;
  completed_at: string | null;
};

export type TaskCenterStats = Record<string, any> & {
  account_coverage?: TaskAccountCoverage;
  hard_hourly_target_enabled?: boolean;
  hard_hourly_goal?: number | null;
  hard_hourly_bucket?: string | null;
  hard_hourly_success_count?: number;
  hard_hourly_open_count?: number;
  hard_hourly_overdue_open_count?: number;
  hard_hourly_deficit?: number;
  hard_hourly_status?: HardHourlyStatus;
  hard_hourly_last_check_at?: string | null;
  hard_hourly_last_planned_count?: number;
  hard_hourly_last_blockers?: HardHourlyBlockers;
  hard_hourly_pipeline?: HardHourlyPipeline;
  hard_hourly_recent_buckets?: HardHourlyRecentBucket[];
};

export type TaskCenterTask = {
  id: string;
  tenant_id: number;
  name: string;
  type: TaskCenterAnyTaskType;
  status: string;
  priority: number;
  timezone: string;
  scheduled_start: string | null;
  scheduled_end: string | null;
  max_duration_hours: number | null;
  next_run_at: string | null;
  last_error: string;
  account_config: Record<string, any>;
  pacing_config: Record<string, any>;
  failure_policy: Record<string, any>;
  type_config: Record<string, any> & Partial<GroupAIChatHardHourlyConfig>;
  stats: TaskCenterStats;
  runtime_stage?: Record<string, any>;
  target_summary?: string;
  search_text?: string;
  created_at: string;
  updated_at: string;
};

export type TaskCenterAction = {
  id: string;
  tenant_id: number;
  task_id: string;
  task_type: string;
  action_type: string;
  account_id: number | null;
  account_display_name?: string;
  account_username?: string | null;
  scheduled_at: string;
  executed_at: string | null;
  status: string;
  payload: Record<string, any>;
  result: Record<string, any>;
  retry_count: number;
  failure_type: string;
  failure_reason: string;
  failure_diagnosis: {
    category?: string;
    scope?: string;
    operator_summary?: string;
    suggested_action?: string;
    [key: string]: any;
  };
  raw_error: string;
  trace_id: string;
  operation_issue_id: string;
  operation_issue_status: string;
  operation_issue_rolled_up: boolean;
  created_at: string;
};

export type TaskExecutionAttempt = {
  id: string;
  tenant_id: number;
  action_id: string;
  worker_id: string;
  account_id: number | null;
  attempt_no: number;
  status: string;
  before_call_at: string | null;
  gateway_call_started_at: string | null;
  after_call_at: string | null;
  remote_message_id: string;
  failure_type: string;
  failure_detail: string;
  result_snapshot: Record<string, any>;
  created_at: string;
};

export type TaskRuntimeSummary = {
  id: string;
  tenant_id: number;
  task_id: string;
  task_status: string;
  target_id: number | null;
  planned_count: number;
  success_count: number;
  failed_count: number;
  pending_count: number;
  oldest_pending_at: string | null;
  latest_failure_type: string;
  summary: Record<string, any>;
  updated_at: string;
};

export type RuleSetVersion = {
  id: number;
  tenant_id: number;
  rule_set_id: number;
  version: number;
  status: string;
  version_note: string;
  filters: Record<string, any>;
  output_checks: Record<string, any>;
  transforms: Record<string, any>;
  routing: Record<string, any>;
  account_strategy: Record<string, any>;
  rate_limits: Record<string, any>;
  retry_policy: Record<string, any>;
  created_by: string;
  published_by: string;
  published_at: string | null;
  created_at: string;
  updated_at: string;
};

export type RuleSet = {
  id: number;
  tenant_id: number;
  name: string;
  description: string;
  status: string;
  task_types: string[];
  default_policy: Record<string, any>;
  active_version_id: number | null;
  versions: RuleSetVersion[];
  created_at: string;
  updated_at: string;
};

export type RuleSetBoundTask = {
  id: string;
  name: string;
  type: string;
  status: string;
  binding_mode: string;
  rule_set_id: number | null;
  rule_set_version_id: number | null;
  resolved_rule_set_version_id: number | null;
  created_at: string;
  updated_at: string;
};

export type TaskMembershipItem = {
  item_id: string;
  latest_action_id: string;
  account_id: number;
  display_name: string;
  username: string;
  status: string;
  phase: string;
  can_send: boolean;
  target_id: number | null;
  target_type: string;
  target_display: string;
  scheduled_at: string | null;
  completed_at: string | null;
  failure_type: string;
  failure_detail: string;
  manual_required: boolean;
  verification_task_id: number | null;
  verification_status: string;
  verification_action: string;
  can_auto_resolve: boolean;
  challenge_question: string;
  recovery_bucket: string;
  recovery_label: string;
  recovery_action: string;
  operator_required: boolean;
  auto_retryable: boolean;
  account_replace_required: boolean;
};

export type TaskMembershipAdmissionItem = {
  id: number;
  account_id: number;
  display_name: string;
  username: string;
  target_id: number;
  phase: string;
  membership_action_id: string | null;
  test_message_action_id: string | null;
  delete_action_id: string | null;
  test_message_text: string;
  test_message_id: string;
  delete_after_send: boolean;
  delete_status: string;
  permission_failure_count: number;
  rescue_action_id: string | null;
  rescue_status: string;
  rescue_failure_detail: string;
  failure_type: string;
  failure_detail: string;
  manual_required: boolean;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
};

export type TaskCenterDetail = {
  task: TaskCenterTask;
  actions: TaskCenterAction[];
  stats: TaskCenterStats;
  task_runtime_summary?: TaskRuntimeSummary | null;
  operation_plan_links?: Array<{ id: number; plan_id: number; target_id: number | null; task_id: string; relation: string; status: string; created_at: string }>;
  accounts: Array<{ id: number; display_name: string; username: string | null; status: string }>;
  membership_phase: Record<string, any>;
  membership_accounts: TaskMembershipItem[];
  membership_admission_phase: Record<string, any>;
  membership_admission_items: TaskMembershipAdmissionItem[];
  account_coverage_items: TaskAccountCoverageItem[];
  learning_profile_preview?: Record<string, any>;
  message_groups: Array<{
    channel_target_id: number | null;
    channel_title: string;
    channel_username: string;
    message_id: number | null;
    action_type: string;
    action_label: string;
    message_url: string;
    content_preview: string;
    target_count: number;
    completed_count: number;
    failed_count: number;
    running_count: number;
    skipped_count: number;
    duplicate_count: number;
    capacity_shortfall: number;
    subtask_status: string;
    stats: Record<string, any>;
    actions: TaskCenterAction[];
  }>;
  ai_cycles: Array<{
    cycle_id: string;
    context_message_ids: number[];
    stats: Record<string, any>;
    turns: Array<{
      action_id: string;
      turn_index: number;
      account_id: number | null;
      account_role: string;
      account_memory: string;
      account_profile: string;
      account_voice_profile_version: number;
      account_voice_profile_summary: string;
      account_voice_profile_match_score: number;
      account_voice_profile_match_reason: string;
      account_mask_version: number;
      account_mask_summary: string;
      account_mask_match_score: number;
      account_mask_match_reason: string;
      stance_summary: string;
      topic_thread: string;
      topic_plan: string;
      intent: string;
      act_type: string;
      generation_source: string;
      quality_decision: string;
      quality_fallback: string;
      ai_message_memory_id: string;
      semantic_cluster: string;
      content: string;
      reply_to_message_id?: number | null;
      reply_target_label?: string;
      reply_target_author?: string;
      reply_target_preview?: string;
      reply_target_source?: string;
      material_intent: string;
      material_matched_tags: string[];
      material_candidate_count: number;
      material_id?: number | null;
      material_failure_reason: string;
      status: string;
      scheduled_at: string;
      executed_at: string | null;
      result: Record<string, any>;
    }>;
  }>;
  ai_generation_records: Array<{
    generation_id: string;
    cycle_id: string;
    status: string;
    generation_source?: string;
    generated_count: number;
    token_count: number;
    context_message_count: number;
    account_memory_count: number;
    profile_scene?: string;
    profile_version?: number;
    profile_hit_summary?: string;
    profile_unavailable_reason?: string;
    quality_risks?: string[];
    skip_reason?: string;
    scheduled_at: string | null;
    created_at: string | null;
  }>;
  ai_account_profiles: Array<{
    account_id: number;
    display_name: string;
    username: string | null;
    status: string;
    total_success_count: number;
    current_task_success_count: number;
    cross_task_success_count: number;
    profile_summary: string;
  }>;
  ai_quality_funnel: {
    totals?: {
      candidate_count?: number;
      passed_count?: number;
      final_send_count?: number;
      action_count?: number;
    };
    reason_counts?: Record<string, number>;
    samples?: Record<string, Array<{
      action_id: string;
      account_id: number | null;
      status: string;
      content: string;
      detail: string;
      scheduled_at: string | null;
    }>>;
  };
  account_online_summary: {
    desired_count?: number;
    online_count?: number;
    warming_count?: number;
    recovering_count?: number;
    relogin_required_count?: number;
    blocked_count?: number;
    stale_count?: number;
    offline_count?: number;
    missing_state_count?: number;
    status_counts?: Record<string, number>;
    samples?: Array<{
      account_id: number;
      online_status: string;
      bucket: string;
      failure_type: string;
      failure_detail: string;
      recovery_status: string;
      last_seen_at: string | null;
      last_probe_at: string | null;
      stale_after_at: string | null;
      desired_sources: Array<Record<string, unknown>>;
    }>;
  };
  relay_batches: Array<{
    relay_batch_id: string;
    stats: Record<string, any>;
    source_event_count: number;
    material_count: number;
    rule_version_count: number;
    items: Array<{
      action_id: string;
      relay_event_id: string;
      source_event_key: string;
      source_group_id: number | null;
      source_operation_target_id: number | null;
	      operation_target_id: number | null;
	      source_info: string;
	      source_group_title: string;
	      source_sender_name: string;
	      source_sender_peer_id: string;
	      source_sender_username: string;
	      source_sender_role: string;
	      source_is_bot: boolean;
	      source_filter_reason: string;
	      source_remote_message_id: string;
      source_message_type: string;
      source_sent_at: string | null;
      target_display: string;
      original_text: string;
      transformed_text: string;
      material_fingerprint: string;
      rule_set_id: number | null;
      rule_set_name: string;
      rule_set_version_id: number | null;
      resolved_rule_set_version_id?: number | null;
      rule_set_version: number | null;
      rule_binding_mode?: string;
      rule_trace: Record<string, any>;
      account_id: number | null;
      status: string;
      retry_count: number;
      scheduled_at: string;
      executed_at: string | null;
      result: Record<string, any>;
	    }>;
	  }>;
  recent_relay_sources: Array<{
	    source_group_id: number | null;
	    source_group_title: string;
	    listener_account_id: number | null;
	    sender_peer_id: string;
	    sender_name: string;
	    sender_username: string;
	    sender_role: string;
	    is_bot: boolean;
	    source_filter_reason: string;
	    content: string;
	    message_type: string;
	    remote_message_id: string;
    sent_at: string | null;
  }>;
  profile_batch?: {
    batch_id: number;
    action_types: string[];
    batch_status: string;
    avatar_cache: Record<string, number>;
    items: Array<{
      account_id: number;
      display_name: string;
      phone_number: string;
      status: string;
      profile_status: string;
      username_status: string;
      avatar_status: string;
      avatar_source: string;
      avatar_cache_status: string;
      avatar_preview_url: string;
      failure_type: string;
      failure_detail: string;
    }>;
  };
  account_security_batch?: {
    batch_id: number;
    system_task_type: TaskCenterSystemTaskType;
    action_types: string[];
    batch_status: string;
    avatar_cache?: Record<string, number>;
    items: Array<{
      account_id: number;
      display_name: string;
      phone_number: string;
      status: string;
      profile_status: string;
      username_status: string;
      avatar_status: string;
      device_cleanup_status?: string;
      two_fa_status?: string;
      standby_session_status?: string;
      target_slot?: string;
      developer_app_label?: string;
      proxy_label?: string;
      verification_code_status?: string;
      two_fa_usage_status?: string;
      preserved_devices_summary?: string;
      cleaned_devices_summary?: string;
      avatar_source: string;
      avatar_cache_status: string;
      avatar_preview_url: string;
      failure_type: string;
      failure_detail: string;
    }>;
  };
	};

export type SearchRankDeboostConfig = {
  per_account_daily_click_limit?: number;
  per_keyword_account_daily_limit?: number;
  group_ip_daily_click_limit?: number;
  max_actions_per_hour?: number;
  per_account_cooldown_hours?: number;
  dwell_seconds_min?: number;
  dwell_seconds_max?: number;
};

export type SearchRankDeboostExemptGroup = {
  task_id: string;
  exempt_group_username: string;
  exempt_group_peer_id: string;
  exempt_group_title: string;
  exempt_group_match_strategy: string;
  selected_at: string;
  selected_by: string;
};

export type TaskPrecheck = {
  task_type: TaskCenterTaskType;
  decision: 'allow' | 'warn' | 'block';
  available_account_count: number;
  candidate_account_count: number;
  limited_account_count: number;
  blocked_account_count: number;
  target_ability: Array<Record<string, any>>;
  target_resolution: Record<string, any>;
  membership_summary: Record<string, any>;
  ready_account_count: number;
  preparable_account_count: number;
  estimated_membership_actions: number;
  membership_warnings: string[];
  membership_subtask_preview: Record<string, any>;
  estimated_actions: number;
  capacity_shortfall: number;
  capacity_summary: {
    target_per_message?: number;
    candidate_account_count?: number;
    effective_account_count?: number;
    max_concurrent?: number;
    capacity_shortfall?: number;
    limit_note?: string;
    reply_reference_summary?: Record<string, any>;
    recommended_limits?: {
      max_actions_per_hour?: number;
      messages_per_round?: number;
      reply_min_per_round?: number;
      target_comments_per_message?: number;
      max_total_comments?: number;
      max_total_comments_jitter?: number;
      reply_min_per_message?: number;
      max_comments_per_account_per_hour?: number;
      current_hour_rounds?: number;
      estimated_hourly_capacity?: number;
      basis?: Record<string, any>;
    };
  };
  hourly_round_curve?: number[];
  current_hour_rounds?: number;
  messages_per_round?: number;
  max_actions_per_hour?: number;
  estimated_hourly_capacity?: number;
  hard_hourly_target?: {
    enabled: boolean;
    hourly_min_messages?: number | null;
    estimated_hourly_capacity?: number | null;
    capacity_gap?: number;
    hard_target_over_capacity?: boolean;
    warnings?: string[];
  };
  round_capacity_explanation?: string;
  rule_version: Record<string, any> | null;
  risk_hits: string[];
  blockers: string[];
  warnings: string[];
  suggested_actions: string[];
  trace_id: string;
};
