"""Static adult vocabulary data partition."""

from __future__ import annotations

from .ai_group_vocabulary_types import ALL_ADULT_ROUTES, VocabularyUnit, _u

def _cat_stmt() -> list[VocabularyUnit]:
    data = [
        (
            "adult_stmt_01",
            ["确实一分钱一分货", "物有所值挺满意的"],
            ["一分钱一分货"],
            [1, 6],
            {"1": 3, "6": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_stmt_02",
            ["这波体验确实值了", "感觉不虚此行"],
            ["体验值得"],
            [1, 5],
            {"1": 3, "5": 2},
            ["detail_follow", "short_react"],
            ["positive"],
            "common",
        ),
        (
            "adult_stmt_03",
            ["太坑了下次不去了", "真是踩了大雷"],
            ["太坑踩雷"],
            [1, 4],
            {"1": 2, "4": 3},
            ["light_disagree", "detail_follow"],
            ["negative"],
            "common",
        ),
        (
            "adult_stmt_04",
            ["笑死这槽吐得犀利", "老哥太逗了"],
            ["调侃犀利"],
            [0, 5],
            {"0": 2, "5": 3},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_stmt_05",
            ["卧槽真假这也行", "竟然还有这出"],
            ["震惊意外"],
            [0, 2, 5],
            {"0": 2, "5": 3},
            ["short_react", "context_reply"],
            ["neutral"],
            "common",
        ),
        (
            "adult_stmt_06",
            ["那还行不算太离谱", "在可接受范围内"],
            ["可接受范围"],
            [1, 4, 6],
            {"1": 2, "4": 2},
            ["detail_follow", "short_react"],
            ["neutral", "positive"],
            "common",
        ),
        (
            "adult_stmt_07",
            ["看着挺顺眼的", "感觉第一印象不错"],
            ["第一印象好"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_stmt_08",
            ["确实是这么个理", "认同老哥说的"],
            ["认同观点"],
            [0, 3, 6],
            {"0": 2, "3": 3},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_stmt_09",
            ["有点一言难尽啊", "只能说仁者见仁"],
            ["一言难尽"],
            [1, 4],
            {"1": 2, "4": 3},
            ["light_disagree", "detail_follow"],
            ["reserved"],
            "rare",
        ),
        (
            "adult_stmt_10",
            ["整体还算过得去吧", "无功无过挺普通的"],
            ["普通中规中矩"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "short_react"],
            ["neutral"],
            "common",
        ),
        (
            "adult_stmt_11",
            ["这评价属实真实", "接地气的反馈"],
            ["评价真实"],
            [1, 3],
            {"1": 2, "3": 2},
            ["context_reply", "detail_follow"],
            ["positive"],
            "rare",
        ),
        (
            "adult_stmt_12",
            ["期待值别拉太满就行", "平常心对待"],
            ["平常心对待"],
            [1, 4, 6],
            {"1": 2, "4": 2},
            ["detail_follow", "short_react"],
            ["neutral", "reserved"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "statement_emotion",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]


def _cat_mini() -> list[VocabularyUnit]:
    data = [
        (
            "adult_mini_01",
            ["确实老哥说得在理", "确实是这么回事"],
            ["确实在理"],
            [0, 3, 6],
            {"0": 3, "3": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_02",
            ["这个点我也认同", "这句说到点上了"],
            ["具体认同"],
            [0, 3],
            {"0": 3, "3": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_03",
            ["先蹲一个后续看看", "蹲一手后续战报"],
            ["蹲后续"],
            [0, 2, 6],
            {"0": 3, "2": 2},
            ["short_react", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_mini_04",
            ["老哥这波总结到位", "总结得挺精辟的"],
            ["总结到位"],
            [0, 3, 5],
            {"0": 2, "5": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_05",
            ["太真实了深有同感", "确实深有体会"],
            ["深有同感"],
            [0, 3],
            {"0": 3, "3": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_06",
            ["同感我也这么觉得", "英雄所见略同"],
            ["同感觉得"],
            [0, 3],
            {"0": 3, "3": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_07",
            ["这个细节先记住", "这点后面能对照"],
            ["细节对照"],
            [0, 6],
            {"0": 2, "6": 2},
            ["short_react", "detail_follow"],
            ["neutral"],
            "rare",
        ),
        (
            "adult_mini_08",
            ["坐等老哥出击归来", "静候老哥佳音"],
            ["坐等出击"],
            [0, 5, 6],
            {"0": 2, "5": 2},
            ["short_react", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_09",
            ["好嘞收到老哥提醒", "收到提醒感谢"],
            ["收到提醒"],
            [0, 3],
            {"0": 3, "3": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_10",
            ["这个判断有依据", "前后逻辑能对上"],
            ["判断有依据"],
            [0, 3, 6],
            {"0": 2, "3": 3},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_mini_11",
            ["不至于吧没那么夸张", "感觉言过其实了"],
            ["没那么夸张"],
            [0, 4],
            {"0": 2, "4": 3},
            ["short_react", "light_disagree"],
            ["reserved"],
            "rare",
        ),
        (
            "adult_mini_12",
            ["看着不错有机会试试", "看着还行有空去"],
            ["有机会试试"],
            [0, 5, 6],
            {"0": 2, "5": 2},
            ["short_react", "detail_follow"],
            ["positive"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "minimal_natural_react",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]
