"""Static adult vocabulary data partition."""

from __future__ import annotations

from .ai_group_vocabulary_types import ALL_ADULT_ROUTES, VocabularyUnit, _u

def _cat_trans() -> list[VocabularyUnit]:
    data = [
        (
            "adult_trans_01",
            ["不过话说回来也看运气", "运气成分挺大的"],
            ["看运气成分"],
            [3, 4, 6],
            {"3": 2, "4": 2},
            ["context_reply", "detail_follow"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_trans_02",
            ["另外问一句有停车位没", "顺便问下好停车不"],
            ["顺便问停车"],
            [2, 3],
            {"2": 3, "3": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_trans_03",
            ["反正我是觉得挺值的", "总归是物有所值"],
            ["反正觉得值"],
            [1, 3],
            {"1": 2, "3": 2},
            ["context_reply", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_trans_04",
            ["话说最近还有新面孔没", "顺便打听下新开课"],
            ["顺便打听新面孔"],
            [2, 3, 6],
            {"2": 3, "3": 2},
            ["question", "topic_shift"],
            ["neutral"],
            "common",
        ),
        (
            "adult_trans_05",
            ["要是这样的话那还行", "那倒还挺让人放心"],
            ["这样的话还行"],
            [3, 6],
            {"3": 3, "6": 2},
            ["context_reply", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_trans_06",
            ["不管怎么说防踩雷要紧", "安全第一最关键"],
            ["防踩雷要紧"],
            [1, 3, 4],
            {"1": 2, "4": 3},
            ["detail_follow", "context_reply"],
            ["reserved"],
            "common",
        ),
        (
            "adult_trans_07",
            ["但凡态度好点也不至于", "主要看服务态度"],
            ["主要看态度"],
            [1, 3, 4],
            {"1": 2, "4": 2},
            ["light_disagree", "detail_follow"],
            ["negative", "reserved"],
            "rare",
        ),
        (
            "adult_trans_08",
            ["所以说熟人带路才稳当", "老带新才靠谱"],
            ["熟人带路稳"],
            [1, 3, 6],
            {"1": 2, "3": 3},
            ["context_reply", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_trans_09",
            ["既然老哥推荐那就信一手", "信老哥一手"],
            ["信老哥推荐"],
            [3, 5],
            {"3": 2, "5": 2},
            ["context_reply", "short_react"],
            ["positive"],
            "rare",
        ),
        (
            "adult_trans_10",
            ["总之大家各取所需吧", "各有所爱吧"],
            ["各取所需"],
            [3, 6],
            {"3": 2, "6": 2},
            ["context_reply", "short_react"],
            ["neutral"],
            "common",
        ),
        (
            "adult_trans_11",
            ["话说回来价格也摆在那", "价位摆在那里"],
            ["价位摆在那里"],
            [1, 3, 6],
            {"1": 2, "3": 2},
            ["context_reply", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_trans_12",
            ["反正我是先观望一下", "我先持保留意见"],
            ["先持保留意见"],
            [3, 4],
            {"3": 2, "4": 3},
            ["light_disagree", "detail_follow"],
            ["reserved"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "transition_continuation",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]


def _cat_pers() -> list[VocabularyUnit]:
    data = [
        (
            "adult_pers_01",
            ["老工兵探路先问问细节", "先帮兄弟们把把关"],
            ["工兵探路把关"],
            [2, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_pers_02",
            ["挑剔老炮眼里容不得沙子", "细节不达标可不行"],
            ["挑剔老炮把关"],
            [1, 4],
            {"1": 3, "4": 3},
            ["light_disagree", "detail_follow"],
            ["reserved"],
            "common",
        ),
        (
            "adult_pers_03",
            ["吃瓜群众路过围观一下", "随性围观老哥交作业"],
            ["吃瓜围观"],
            [0, 5],
            {"0": 3, "5": 2},
            ["short_react", "context_reply"],
            ["neutral"],
            "common",
        ),
        (
            "adult_pers_04",
            ["本地地胆熟门熟路了", "这片商圈我还算熟"],
            ["本地地胆熟路"],
            [1, 3, 6],
            {"1": 2, "3": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_pers_05",
            ["谨慎为上先打听清楚", "谋定而后动"],
            ["谨慎打听"],
            [2, 4],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["reserved"],
            "common",
        ),
        (
            "adult_pers_06",
            ["老司机凭经验说话", "看多了自然懂"],
            ["经验老道"],
            [1, 5, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_pers_07",
            ["新手求老哥们多带带", "萌新初来乍到"],
            ["萌新初来"],
            [2, 5],
            {"2": 2, "5": 2},
            ["question", "context_reply"],
            ["neutral"],
            "rare",
        ),
        (
            "adult_pers_08",
            ["佛系随缘不强求", "合眼缘最重要"],
            ["佛系合眼缘"],
            [0, 6],
            {"0": 2, "6": 2},
            ["short_react", "context_reply"],
            ["neutral"],
            "common",
        ),
        (
            "adult_pers_09",
            ["实干派老哥讲究效率", "干脆利落不墨迹"],
            ["讲究效率"],
            [0, 1],
            {"0": 2, "1": 2},
            ["short_react", "detail_follow"],
            ["positive"],
            "rare",
        ),
        (
            "adult_pers_10",
            ["爱较真的老哥看重细节", "每个环节都得核对"],
            ["较真看重细节"],
            [1, 4],
            {"1": 2, "4": 2},
            ["detail_follow", "light_disagree"],
            ["reserved"],
            "rare",
        ),
        (
            "adult_pers_11",
            ["热心肠老哥乐意分享", "互相交流少踩坑"],
            ["热心分享交流"],
            [1, 3, 5],
            {"1": 2, "5": 2},
            ["context_reply", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_pers_12",
            ["潜水老哥偶尔冒个泡", "出来透个气说两句"],
            ["潜水偶尔冒泡"],
            [0, 5],
            {"0": 3, "5": 2},
            ["short_react", "context_reply"],
            ["neutral"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "persona_nuance",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]
