"""Static adult vocabulary data partition."""

from __future__ import annotations

from .ai_group_vocabulary_types import ALL_ADULT_ROUTES, VocabularyUnit, _u

def _cat_sch() -> list[VocabularyUnit]:
    data = [
        (
            "adult_sch_01",
            ["最近排课挺满的吧", "今天能约上不"],
            ["排课约期"],
            [2, 4, 6],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_sch_02",
            ["提前多久预约合适", "得提前约不"],
            ["提前预约"],
            [2, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_sch_03",
            ["周末档期紧得很", "周末估计跑空"],
            ["周末档期"],
            [1, 4, 6],
            {"1": 2, "4": 2},
            ["detail_follow", "short_react"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_sch_04",
            ["刚开课的新面孔吗", "新老师开课没"],
            ["新面孔开课"],
            [2, 4, 6],
            {"2": 3, "4": 3},
            ["question", "topic_shift"],
            ["neutral"],
            "common",
        ),
        (
            "adult_sch_05",
            ["休假几天刚回来", "最近回老家了没"],
            ["休假归来"],
            [2, 3, 6],
            {"2": 2, "3": 2},
            ["question", "context_reply"],
            ["neutral"],
            "common",
        ),
        (
            "adult_sch_06",
            ["听说快上岸了真的假的", "还在这边做不"],
            ["上岸传闻"],
            [2, 4],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["reserved"],
            "rare",
        ),
        (
            "adult_sch_07",
            ["下午场时间挺充裕", "下午去人少"],
            ["下午场充裕"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_sch_08",
            ["晚上高峰期得排队", "晚上得等挺久"],
            ["晚上排队"],
            [1, 4, 6],
            {"1": 2, "4": 2},
            ["detail_follow", "light_disagree"],
            ["reserved", "neutral"],
            "common",
        ),
        (
            "adult_sch_09",
            ["档期排到后天了", "这几天都没空档"],
            ["档期紧俏"],
            [1, 4],
            {"1": 2, "4": 2},
            ["detail_follow", "context_reply"],
            ["neutral"],
            "rare",
        ),
        (
            "adult_sch_10",
            ["现在过去方便不", "现在能空出来不"],
            ["即时空档"],
            [2, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_sch_11",
            ["临时改时间麻烦不", "能调时间不"],
            ["调换时间"],
            [2, 4],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["neutral", "reserved"],
            "rare",
        ),
        (
            "adult_sch_12",
            ["趁早约靠谱点", "晚了容易跑空"],
            ["趁早预约"],
            [0, 1, 6],
            {"0": 2, "1": 3},
            ["short_react", "detail_follow"],
            ["positive", "neutral"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "schedule_timing",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]


def _cat_caut() -> list[VocabularyUnit]:
    data = [
        (
            "adult_caut_01",
            ["先蹲个真实战报", "蹲一手老哥反馈"],
            ["蹲战报"],
            [0, 2, 6],
            {"0": 2, "2": 3, "6": 3},
            ["short_react", "detail_follow"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_caut_02",
            ["这波别盲冲先观望", "先观望几天"],
            ["观望别盲冲"],
            [0, 4, 6],
            {"0": 2, "4": 3},
            ["short_react", "light_disagree"],
            ["reserved"],
            "common",
        ),
        (
            "adult_caut_03",
            ["有没有踩雷的老哥", "有人踩过雷没"],
            ["打听踩雷"],
            [2, 4, 6],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_caut_04",
            ["老哥这评价挺中肯", "中肯的避坑提醒"],
            ["中肯评价"],
            [1, 3, 6],
            {"1": 2, "3": 3},
            ["context_reply", "short_react"],
            ["positive"],
            "common",
        ),
        (
            "adult_caut_05",
            ["水军吹得太玄乎了", "感觉宣传有点过"],
            ["警惕吹嘘"],
            [1, 4],
            {"1": 2, "4": 3},
            ["light_disagree", "detail_follow"],
            ["negative", "reserved"],
            "common",
        ),
        (
            "adult_caut_06",
            ["求老熟客指路", "有常去的老哥没"],
            ["求熟客指路"],
            [2, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_caut_07",
            ["避开高峰期更稳妥", "错峰去稳一点"],
            ["错峰稳妥"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_caut_08",
            ["听劝不盲目冲", "感谢老哥提醒"],
            ["听劝感谢"],
            [0, 3],
            {"0": 2, "3": 3},
            ["short_react", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_caut_09",
            ["看着有点像照骗", "心里稍微有点打鼓"],
            ["心存疑虑"],
            [1, 4],
            {"1": 2, "4": 3},
            ["light_disagree", "detail_follow"],
            ["reserved"],
            "common",
        ),
        (
            "adult_caut_10",
            ["老哥稳少走弯路", "省了不少冤枉路"],
            ["老哥稳少走弯路"],
            [0, 1, 5],
            {"0": 2, "5": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_caut_11",
            ["不确定先不轻易下结论", "再看看评价"],
            ["再看评价"],
            [4, 6],
            {"4": 3, "6": 2},
            ["light_disagree", "detail_follow"],
            ["reserved"],
            "rare",
        ),
        (
            "adult_caut_12",
            ["亲身体验才算数", "道听途说不可全信"],
            ["亲身体验才算"],
            [1, 4, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "short_react"],
            ["neutral", "reserved"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "cautious_verification",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]
