"""Static adult vocabulary data partition."""

from __future__ import annotations

from .ai_group_vocabulary_types import ALL_ADULT_ROUTES, VocabularyUnit, _u

def _cat_coop() -> list[VocabularyUnit]:
    data = [
        (
            "adult_coop_01",
            ["配合度挺高的", "配合挺到位"],
            ["配合度高"],
            [1, 3, 6],
            {"1": 2, "3": 3},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_coop_02",
            ["节奏不赶挺放松", "不慌不忙挺好"],
            ["节奏不赶"],
            [0, 1, 5],
            {"0": 2, "1": 2},
            ["short_react", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_coop_03",
            ["动作挺轻柔的", "挺温柔细致"],
            ["轻柔温柔"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_coop_04",
            ["细节做得挺到位", "流程挺规范"],
            ["细节到位"],
            [1, 6],
            {"1": 3, "6": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_coop_05",
            ["配合度怎么样求问", "配合度行不行"],
            ["求问配合"],
            [2, 6],
            {"2": 3, "6": 1},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_coop_06",
            ["过程挺投入的不糊弄", "挺走心的"],
            ["投入不糊弄"],
            [1, 3, 5],
            {"1": 2, "3": 3},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_coop_07",
            ["动作生疏不老哥", "熟练度咋样"],
            ["打听熟练"],
            [2, 4],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_coop_08",
            ["手法挺娴熟的", "挺有经验的"],
            ["手法娴熟"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_coop_09",
            ["时间过得挺快的", "感觉一眨眼就到了"],
            ["时间过得快"],
            [0, 5],
            {"0": 2, "5": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_coop_10",
            ["节奏把控得不错", "有条不紊的"],
            ["节奏把控"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "short_react"],
            ["positive"],
            "common",
        ),
        (
            "adult_coop_11",
            ["不糊弄事挺规矩", "挺敬业的"],
            ["不糊弄敬业"],
            [1, 3],
            {"1": 2, "3": 3},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_coop_12",
            ["服务细节拉满", "体验挺丝滑"],
            ["细节拉满"],
            [1, 5, 6],
            {"1": 2, "5": 2},
            ["detail_follow", "short_react"],
            ["positive"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "cooperation_pacing",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]


def _cat_env() -> list[VocabularyUnit]:
    data = [
        (
            "adult_env_01",
            ["公寓隔音效果好不", "隔音怎么样"],
            ["隔音效果"],
            [2, 4, 6],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_env_02",
            ["楼下停车方便吗", "车位好找不"],
            ["楼下停车"],
            [2, 5, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_env_03",
            ["电梯需要刷卡不", "进门麻烦不"],
            ["电梯刷卡"],
            [2, 4],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["neutral", "reserved"],
            "common",
        ),
        (
            "adult_env_04",
            ["房间打扫得挺干净", "卫生收拾得挺整洁"],
            ["房间干净"],
            [1, 3, 6],
            {"1": 2, "3": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_env_05",
            ["空调挺给力的", "温度刚好挺舒服"],
            ["空调温度"],
            [0, 5],
            {"0": 2, "5": 2},
            ["short_react", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_env_06",
            ["位置挺好找的不用绕", "导航直接能到"],
            ["位置好找"],
            [1, 3],
            {"1": 2, "3": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_env_07",
            ["周边挺安静的私密", "私密性挺好"],
            ["安静私密"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "short_react"],
            ["positive"],
            "common",
        ),
        (
            "adult_env_08",
            ["换新地方了还是老位置", "换场子没"],
            ["换场位置"],
            [2, 3, 6],
            {"2": 3, "3": 2},
            ["question", "topic_shift"],
            ["neutral"],
            "common",
        ),
        (
            "adult_env_09",
            ["环境布置挺温馨", "不是那种简陋毛坯"],
            ["环境温馨"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_env_10",
            ["离地铁口近不近", "步行远不远"],
            ["地铁步行"],
            [2, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_env_11",
            ["门禁严不严老哥", "安全系数高不高"],
            ["门禁安全"],
            [2, 4],
            {"2": 3, "4": 3},
            ["question", "detail_follow"],
            ["reserved", "neutral"],
            "common",
        ),
        (
            "adult_env_12",
            ["屋里没异味挺清爽", "通风挺好的"],
            ["屋里无味清爽"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "short_react"],
            ["positive"],
            "rare",
        ),
    ]
    return [
        _u(
            vid,
            "environment_access",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]
