"""Static adult vocabulary data partition."""

from __future__ import annotations

from .ai_group_vocabulary_types import ALL_ADULT_ROUTES, VocabularyUnit, _u

def _cat_app() -> list[VocabularyUnit]:
    data = [
        (
            "adult_app_01",
            ["素颜看着挺顺眼", "素颜看着舒服"],
            ["素颜顺眼"],
            [1, 5, 6],
            {"1": 3, "6": 2},
            ["detail_follow", "short_react"],
            ["positive", "neutral"],
            "common",
        ),
        (
            "adult_app_02",
            ["真人比照片显瘦", "真人比图显瘦"],
            ["真人显瘦"],
            [1, 2, 6],
            {"1": 3, "2": 2},
            ["detail_follow", "context_reply"],
            ["positive", "neutral"],
            "common",
        ),
        (
            "adult_app_03",
            ["身材比例还过得去", "身材挺匀称"],
            ["身材匀称"],
            [0, 1, 6],
            {"0": 2, "1": 3},
            ["detail_follow", "short_react"],
            ["positive", "neutral"],
            "common",
        ),
        (
            "adult_app_04",
            ["五官挺端正的", "长相挺清秀"],
            ["长相清秀"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_app_05",
            ["修图痕迹有点明显", "这图修得有点狠"],
            ["修图明显"],
            [1, 2, 4],
            {"1": 3, "4": 2},
            ["detail_follow", "light_disagree"],
            ["negative", "reserved"],
            "common",
        ),
        (
            "adult_app_06",
            ["实物跟海报差多少", "实物跟照片像吗"],
            ["实物对比"],
            [2, 6],
            {"2": 3, "6": 1},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_app_07",
            ["微胖看着挺有肉感", "稍微有点微胖"],
            ["微胖肉感"],
            [0, 1, 5],
            {"0": 2, "5": 2},
            ["short_react", "detail_follow"],
            ["positive", "neutral"],
            "common",
        ),
        (
            "adult_app_08",
            ["个子高挑腿型不错", "个头看着挺高"],
            ["高挑腿型"],
            [1, 6],
            {"1": 2, "6": 2},
            ["detail_follow", "short_react"],
            ["positive"],
            "common",
        ),
        (
            "adult_app_09",
            ["气质看着挺文静", "举止挺随和"],
            ["气质文静"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_app_10",
            ["原相机拍的么", "这照片有滤镜没"],
            ["原相机滤镜"],
            [2, 4],
            {"2": 3, "4": 2},
            ["question", "detail_follow"],
            ["reserved"],
            "common",
        ),
        (
            "adult_app_11",
            ["长发及腰挺有辨识度", "短发看着干练"],
            ["辨识度发型"],
            [0, 1],
            {"0": 2, "1": 2},
            ["detail_follow", "short_react"],
            ["positive", "neutral"],
            "rare",
        ),
        (
            "adult_app_12",
            ["照片角度找得挺好", "角度看着挺显身材"],
            ["拍照角度"],
            [1, 4, 6],
            {"1": 2, "4": 2},
            ["light_disagree", "detail_follow"],
            ["reserved", "neutral"],
            "common",
        ),
        (
            "adult_app_13",
            ["骨相看着挺年轻", "长相挺耐看的"],
            ["耐看骨相"],
            [1, 5],
            {"1": 2, "5": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
    ]
    return [
        _u(
            vid,
            "appearance_authenticity",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]


def _cat_att() -> list[VocabularyUnit]:
    data = [
        (
            "adult_att_01",
            ["态度挺温和不机车", "说话挺客气的"],
            ["态度温和"],
            [1, 3, 5],
            {"1": 2, "3": 3},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_att_02",
            ["脾气好挺有耐心", "挺有耐心的"],
            ["脾气好耐心"],
            [1, 3, 6],
            {"1": 2, "3": 3},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_att_03",
            ["说话直爽不绕弯", "交流挺顺畅"],
            ["直爽顺畅"],
            [0, 5],
            {"0": 2, "5": 3},
            ["short_react", "context_reply"],
            ["positive", "neutral"],
            "common",
        ),
        (
            "adult_att_04",
            ["态度敷衍不", "服务态度咋样"],
            ["打听态度"],
            [2, 6],
            {"2": 3, "6": 2},
            ["question", "detail_follow"],
            ["neutral"],
            "common",
        ),
        (
            "adult_att_05",
            ["挺会照顾情绪", "感觉挺贴心的"],
            ["贴心照顾"],
            [1, 3, 5],
            {"1": 2, "5": 2},
            ["context_reply", "detail_follow"],
            ["positive"],
            "rare",
        ),
        (
            "adult_att_06",
            ["催钟严重不老哥", "时间给得足不"],
            ["打听催钟"],
            [2, 4],
            {"2": 3, "4": 3},
            ["question", "detail_follow"],
            ["reserved", "neutral"],
            "common",
        ),
        (
            "adult_att_07",
            ["不催时间挺踏实的", "时间卡得不紧"],
            ["不催时间"],
            [1, 3, 6],
            {"1": 3, "3": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
        (
            "adult_att_08",
            ["进门笑脸相迎挺热情", "挺热情的"],
            ["热情进门"],
            [1, 5],
            {"1": 2, "5": 3},
            ["detail_follow", "context_reply"],
            ["positive"],
            "rare",
        ),
        (
            "adult_att_09",
            ["聊天不尴尬挺能聊", "挺聊得来的"],
            ["聊天不尴尬"],
            [3, 5, 6],
            {"3": 2, "5": 2},
            ["context_reply", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_att_10",
            ["有点爱搭不理的", "感觉回复挺慢"],
            ["冷淡爱搭不理"],
            [1, 4],
            {"1": 2, "4": 3},
            ["light_disagree", "detail_follow"],
            ["negative", "reserved"],
            "common",
        ),
        (
            "adult_att_11",
            ["说话挺实在的", "不吹嘘挺实在"],
            ["说话实在"],
            [0, 1, 6],
            {"0": 2, "1": 3},
            ["short_react", "detail_follow"],
            ["positive"],
            "common",
        ),
        (
            "adult_att_12",
            ["态度好配合度高", "态度稳当"],
            ["态度好配合"],
            [1, 3, 6],
            {"1": 3, "6": 2},
            ["detail_follow", "context_reply"],
            ["positive"],
            "common",
        ),
    ]
    return [
        _u(
            vid,
            "attitude_communication",
            surfs,
            norms,
            tags,
            w,
            ALL_ADULT_ROUTES,
            acts,
            st,
            rarity=r,
        )
        for vid, surfs, norms, tags, w, acts, st, r in data
    ]
