from __future__ import annotations

from app.schemas.task_center import (
    ChannelCommentConfig,
    ChannelCommentTaskCreate,
    ChannelLikeConfig,
    ChannelLikeTaskCreate,
    ChannelViewConfig,
    ChannelViewTaskCreate,
    GroupAIChatConfig,
    GroupAIChatTaskCreate,
    GroupMembershipAdmissionConfig,
    GroupMembershipAdmissionTaskCreate,
    GroupRelayConfig,
    GroupRelayTaskCreate,
    SearchJoinGroupConfig,
    SearchJoinGroupTaskCreate,
)

TYPE_CONFIG_MODELS = {
    "group_ai_chat": GroupAIChatConfig,
    "group_relay": GroupRelayConfig,
    "group_membership_admission": GroupMembershipAdmissionConfig,
    "channel_view": ChannelViewConfig,
    "channel_like": ChannelLikeConfig,
    "channel_comment": ChannelCommentConfig,
    "search_join_group": SearchJoinGroupConfig,
}
TASK_CREATE_MODELS = {
    "group_ai_chat": GroupAIChatTaskCreate,
    "group_relay": GroupRelayTaskCreate,
    "group_membership_admission": GroupMembershipAdmissionTaskCreate,
    "channel_view": ChannelViewTaskCreate,
    "channel_like": ChannelLikeTaskCreate,
    "channel_comment": ChannelCommentTaskCreate,
    "search_join_group": SearchJoinGroupTaskCreate,
}
CHANNEL_DYNAMIC_TASK_TYPES = {"channel_view", "channel_like", "channel_comment"}

COMMON_CREATE_FIELDS = {
    "name",
    "priority",
    "timezone",
    "scheduled_start",
    "scheduled_end",
    "max_duration_hours",
    "account_config",
    "pacing_config",
    "failure_policy",
}

COMMON_SETTINGS_FIELDS = {
    "name",
    "priority",
    "timezone",
    "scheduled_start",
    "scheduled_end",
    "max_duration_hours",
    "account_config",
    "pacing_config",
    "failure_policy",
}

GROUP_AI_LEGACY_RUNTIME_FIELDS = {
    "participation_jitter",
    "silent_mode_enabled",
    "silent_start",
    "silent_end",
    "silent_max_accounts",
    "silent_messages_per_round",
    "ramp_up_minutes",
    "ramp_start_ratio",
}

GROUP_RELAY_LEGACY_CREATE_FIELDS = {
    "monitor_account_ids",
    "filters",
    "rewrite_prompt",
    "preserve_media",
    "add_source_attribution",
    "dedup_window_minutes",
    "dedup_method",
}

CHANNEL_JITTER_FIELDS = {
    "channel_view": {"view_count_jitter"},
    "channel_like": {"like_count_jitter"},
    "channel_comment": {"comment_count_jitter"},
}

LEGACY_PACING_FIELDS = {
    "interval_seconds_min",
    "interval_seconds_max",
    "curve_type",
    "curve_duration_hours",
    "template",
    "jitter_percent",
    "quiet_hours",
}

SEARCH_JOIN_PACING_FIELDS = {
    "per_account_total_action_limit",
    "per_account_daily_action_limit",
    "per_account_cooldown_days",
    "per_keyword_account_daily_limit",
    "max_actions_per_day",
    "hourly_skip_probability",
    "daily_skip_probability",
    "skip_probability_per_action",
    "hourly_jitter_percent",
    "daily_jitter_percent",
}

SEARCH_RANK_DEBOOST_CONFIG_FIELDS = {
    "per_account_daily_click_limit": {"type": "int", "default": 5, "min": 1, "max": 50, "description": "单账号每日点击竞争群数上限"},
    "per_keyword_account_daily_limit": {"type": "int", "default": 2, "min": 1, "max": 20, "description": "单账号每关键词每日点击上限"},
    "group_ip_daily_click_limit": {"type": "int", "default": 50, "min": 1, "max": 500, "description": "单分组共享出口 IP 每日点击上限"},
    "max_actions_per_hour": {"type": "int", "default": 10, "min": 1, "max": 100, "description": "任务级每小时点击上限"},
    "per_account_cooldown_hours": {"type": "int", "default": 4, "min": 0, "max": 168, "description": "同账号两次 action 之间至少间隔小时数"},
    "dwell_seconds_min": {"type": "int", "default": 10, "min": 5, "max": 60, "description": "停留最短秒数"},
    "dwell_seconds_max": {"type": "int", "default": 30, "min": 10, "max": 120, "description": "停留最长秒数"},
}

TYPE_SETTINGS_FIELDS = {
    "group_ai_chat": {
        "target_group_id",
        "target_operation_target_id",
        "rule_set_id",
        "rule_set_version_id",
        "target_group_name",
        "topic_directions",
        "teacher_targets",
        "chat_history_depth",
        "ai_model",
        "system_prompt_override",
        "slang_prompt_template_id",
        "slang_terms",
        "tone",
        "language",
        "max_message_length",
        "participation_rate",
        "participation_jitter",
        "allow_account_repeat",
        "repeat_cooldown_rounds",
        "account_personas",
        "account_memory_depth",
        "messages_per_round_mode",
        "messages_per_round",
        "reply_min_per_round",
        "consecutive_message_enabled",
        "consecutive_message_min",
        "consecutive_message_max",
        "consecutive_message_probability",
        "account_coverage_mode",
        "per_account_daily_min_messages",
        "per_account_daily_max_messages",
        "coverage_window_hours",
        "hard_hourly_target_enabled",
        "hourly_min_messages",
        "hard_hourly_strategy",
        "history_fetch_account_id",
        "auto_join_target",
        "auto_follow_required_channel",
        "auto_resolve_verification",
        "ai_assisted_verification",
        "captcha_failure_policy",
        "membership_max_concurrent",
        "idle_continuation_enabled",
        "idle_continuation_seconds",
        "fact_anchor_required",
        "semantic_repeat_window",
        "low_confidence_silence_enabled",
        "silent_mode_enabled",
        "silent_start",
        "silent_end",
        "silent_max_accounts",
        "silent_messages_per_round",
        "ramp_up_minutes",
        "ramp_start_ratio",
        "context_expire_after_messages",
    },
    "group_relay": {
        "source_groups",
        "rule_set_id",
        "rule_set_version_id",
        "monitor_account_ids",
        "filters",
        "target_group_id",
        "target_operation_target_id",
        "target_group_ids",
        "target_operation_target_ids",
        "content_mode",
        "rewrite_prompt",
        "preserve_media",
        "add_source_attribution",
        "filter_bot_messages",
        "filter_admin_messages",
        "excluded_sender_peer_ids",
        "excluded_sender_usernames",
        "excluded_sender_names",
        "dedup_window_minutes",
        "dedup_method",
        "require_review",
    },
    "group_membership_admission": {
        "target_operation_target_id",
        "account_group_ids",
        "admission_pacing",
        "test_message",
    },
    "channel_view": {
        "target_views_per_message",
        "initial_message_scope",
        "latest_message_count",
        "listen_new_messages",
        "per_message_daily_view_target",
        "per_message_total_view_target",
        "message_active_days",
        "task_daily_view_safety_cap",
        "max_views_per_account_per_day",
        "view_count_jitter",
        "execution_mode",
    },
    "channel_like": {
        "target_likes_per_message",
        "like_count_jitter",
        "reaction_type",
        "allowed_reactions",
        "max_likes_per_account_per_hour",
    },
    "channel_comment": {
        "target_comments_per_message",
        "comment_count_jitter",
        "max_total_comments",
        "max_total_comments_jitter",
        "comment_mode",
        "reply_to_message_ids",
        "reply_min_per_message",
        "rule_set_id",
        "rule_set_version_id",
        "ai_model",
        "comment_style",
        "topic_hint",
        "system_prompt_override",
        "language",
        "max_comment_length",
        "max_comments_per_account_per_hour",
        "require_review",
    },
    "search_join_group": {
        "target_operation_target_id",
        "target_group_id",
        "target_input",
        "target_title",
        "execution_mode",
        "search_bots",
        "max_pages",
        "keyword_hashes",
        "business_region",
        "account_locale",
        "proxy_country",
        "pre_join_decoy_click_min",
        "pre_join_decoy_click_max",
        "post_join_safe_navigation_min",
        "post_join_safe_navigation_max",
        "decoy_join_enabled",
        "hourly_round_curve",
        "actions_per_round",
        "max_actions_per_hour",
        "hourly_min_successful_joins",
        "target_relevance_score",
        "target_content_health",
        "jisou_ecosystem_status",
        "paid_keyword_ad_status",
        "search_visibility_attribution",
        "post_join_policy",
        "post_join_task_links",
    },
}
